version: '3'

services:
  medusa:
    build:
      context: ./marketplace-app
      dockerfile: Dockerfile
    container_name: marketplace-medusa
    depends_on:
      - postgres
    ports:
      - "9000:9000"
    environment:
      NODE_ENV: production
      # local only
      # LOCAL_INSECURE_AUTH: "true"
      STORE_CORS: "https://store.vintagevault.gr"
      ADMIN_CORS: "https://api.vintagevault.gr"
      AUTH_CORS: "https://api.vintagevault.gr"
      DATABASE_URL: "postgresql://marketplace:super-secure-password@postgres:5432/marketplace"
      JWT_SECRET: "supersecret"
      COOKIE_SECRET: "supersecret"
    volumes:
      - medusa-static:/app/.medusa/server/static
      - ./marketplace-app/.env.docker:/app/.medusa/server/.env.production:ro
    networks:
      - internal

  postgres:
    image: postgres:${POSTGRES_VERSION:-15.3-alpine}
    container_name: ${PROJECT_NAME:-marketplace-db}-postgres
    environment:
      POSTGRES_DB: marketplace
      POSTGRES_USER: marketplace
      POSTGRES_PASSWORD: super-secure-password
      PGDATA: '/var/lib/postgresql/data'
      POSTGRES_INITDB_ARGS: '-E UTF8 --locale=C'
    command: ['postgres', '-cshared_preload_libraries=pg_stat_statements']
    ports:
      - 5432:5432
    volumes:
      - marketplace-db-data:/var/lib/postgresql/data
    networks:
      - internal

networks:
  internal:
    name: ${PROJECT_NAME:-marketplace}

volumes:
  marketplace-db-data:
    name: ${POSTGRES_VOLUME_NAME:-marketplace-db-data}
  medusa-static:
    name: ${PROJECT_NAME:-marketplace}-static